/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bcflynn' at '9/20/16 3:55 PM' with Gradle 2.14.1
 *
 * @author bcflynn, @date 9/20/16 3:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
